#!/bin/bash
# OpenRouter Model Setup Script
# Run this to configure all agents with their assigned OpenRouter models

echo "========================================="
echo "OpenRouter Model Assignment Setup"
echo "========================================="
echo ""
echo "This script documents the model assignments for each agent."
echo "To implement, update each agent's session configuration."
echo ""
echo "Agent Model Assignments:"
echo "-----------------------"
echo ""
echo "1. Lui (COO/Orchestrator)"
echo "   Model: deepseek/deepseek-chat"
echo "   Cost: Prompt: \$0.00000014, Completion: \$0.00000028"
echo "   Context: 128k"
echo ""
echo "2. Warren (Strategy Chief)"
echo "   Model: deepseek/deepseek-chat"
echo "   Cost: Prompt: \$0.00000014, Completion: \$0.00000028"
echo "   Context: 128k"
echo ""
echo "3. Brains (Memory Officer)"
echo "   Model: google/gemma-4-31b-it:free"
echo "   Cost: FREE"
echo "   Context: 262k"
echo ""
echo "4. Buzz (Creative/YouTube)"
echo "   Model: qwen/qwen3.5-9b"
echo "   Cost: Prompt: \$0.00000005, Completion: \$0.00000015"
echo "   Context: 256k"
echo ""
echo "5. Lens (Media Producer)"
echo "   Model: amazon/nova-micro-v1"
echo "   Cost: Prompt: \$0.000000035, Completion: \$0.00000014"
echo "   Context: 128k"
echo ""
echo "6. Elon (CTO)"
echo "   Model: qwen/qwen3-coder:free"
echo "   Cost: FREE"
echo "   Context: 262k"
echo ""
echo "7. Goldie (Marketing Chief)"
echo "   Model: google/gemma-4-26b-a4b-it:free"
echo "   Cost: FREE"
echo "   Context: 262k"
echo ""
echo "8. June (Life Manager)"
echo "   Model: meta-llama/llama-3.3-70b-instruct:free"
echo "   Cost: FREE"
echo "   Context: 65k"
echo ""
echo "========================================="
echo "Cost Summary:"
echo "========================================="
echo "- 4 FREE agents: Brains, Elon, Goldie, June"
echo "- 2 Ultra-low cost: Buzz, Lens"
echo "- 2 Low-cost: Lui, Warren"
echo ""
echo "Estimated Monthly Cost (moderate usage):"
echo "- Free models: \$0.00"
echo "- Ultra-low cost: \$0.04-0.20"
echo "- Low-cost: \$0.20-0.40"
echo "- TOTAL: \$0.24 - \$0.60"
echo ""
echo "Savings vs all DeepSeek: 60-70%"
echo ""
echo "========================================="
echo "Implementation Notes:"
echo "========================================="
echo "1. Ensure OpenRouter API key is configured"
echo "2. Update agent session configs with model IDs"
echo "3. Test each agent with new model"
echo "4. Monitor performance and costs"
echo ""
echo "See OPENROUTER_MODEL_ASSIGNMENT.md for details."